### ISSUE TITLE
[Troubleshooting] [Git Push] refusing to allow an OAuth App to create or update workflow ... without `workflow` scope

### ISSUE THREAD

**Issue by JeroCaller** [JeroCaller/Spoon-Suits#54]
# 문제
Github Actions에 사용될 yml 파일을 깃허브에 push 하려다가 다음의 에러를 만나면서 push에 실패함.
```
 ! [remote rejected] feature/github-action-release -> feature/github-action-release (refusing to allow an OAuth App to create or update workflow `.github/workflows/tag-and-release-versioning.yml` without `workflow` scope)
```

# 배경
* Git GUI : SourceTree
* 개발 환경 OS : Window 10
* Intellij에서 yml 파일 작성함.
* Github의 태그 및 릴리즈 자동화를 위한 workflow 파일을 작성하여 push하려고 했음. 해당 yml 코드는 다음과 같음.
```yaml
name: Release versioning
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Automation of Github release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Log created release info
        run: |
          echo "Release Type : ${{ steps.tag_version.outputs.release_type }}"
          echo "Previous Tag : ${{ steps.tag_version.outputs.previous_tag }}"
          echo "New Tag: ${{ steps.tag_version.outputs.new_tag }}"
```

# 예상되는 문제 해결책 - hypo

1. Github에서 Workflow scope 권한 부여
References [1], [2] 참고함.

# 문제 해결을 위한 시도 - try

1. Github에서 PAT(Personal Access Token) 발급 후 windows 자격 증명 암호 갱신 - ✅ 

문제 해결 과정
(1) Github에서 PAT 발급
(1-1) Github 화면 우상단의 프로필 사진 클릭 후 나오는 사이드바에서 -> settings  클릭.
<div style="text-align: center;">
    <img src="https://github.com/user-attachments/assets/77384972-1f94-466b-8cb7-9e3aca59fb05" width="50%" alt="사이드바" />
</div>
(1-2) 다른 화면이 뜨는데, 왼쪽 사이드바 메뉴에서 "Developer settings" 클릭
(1-3) 왼쪽 사이드바 메뉴에서 "Personal access Token" -> "Token(classics)" -> "Generate new Token"을 클릭하여 새 PAT 발급한다.
<div style="text-align: center;">
    <img src="https://github.com/user-attachments/assets/5a62f57a-5b78-463c-ace9-b0a687828f60" width="90%" alt="PAT 메뉴 화면" />
</div>

(1-4) 토큰 생성을 위한 여러 설정이 나오는데, 그 중 "workflow" 체크 박스에 체크를 한다. 나머지 설정은 본인이 필요한대로 설정한다. 
<div style="text-align: center;">
    <img src="https://github.com/user-attachments/assets/69cc3bd5-391f-4dd1-9174-cec55b2cc0af" width="90%" alt="PAT 생성 화면" />
</div>

(1-5) 발급 버튼을 누르면 한 화면에서 PAT 토큰이 나온다. 이 토큰은 인증 수단으로 절대 외부에 노출되어선 안되며, 또한 해당 화면에서 벗어나면 그 토큰값을 영영 다시 볼 수 없기에(이 경우 재발급해야 함) 외부에 노출되지 않을 안전한 곳에 메모를 해둔다. 

이렇게 Github에서 발급한 PAT는 다음 과정에서 필요하다.

(2) Windows 10 기준 로컬 기기에서 자격 증명 암호 갱신
(2-1) 제어판 -> 사용자 계정 -> Windows 자격 증명 관리를 차례대로 눌러 들어간다.
(2-2) 그러면 아래 목록이 뜨는데, 그 중 `git:https://<사용자 깃허브 닉네임>@github.com`이 뜬다. 이 항목을 펼친다. 
(2-3) 그러면 사용자 이름, 암호 등이 뜬다(암호는 별표 처리되어 있다). 그 아래 "편집" 버튼을 누른다.
(2-4) 그러면 암호 등을 편집할 수 있게 되는데, 암호란에 앞서 발급받은 PAT를 북사, 붙여넣기 하고 저장한다. 
(2-5) 혹시 모르니 SourceTree 등 관련 프로그램을 켜둔 상태라면 껐다가 킨다. 
(2-6) 그러면 이 이슈에서 언급한 문제를 해결할 수 있게 된다. 정상적으로 push가 된다. 

단, References에 알려진 대로 자격 증명 중 `git:https://github.com` 이 있는데, 이 자격 증명의 암호를 바꿔도 문제가 해결되지 않았다. 그래서 이 경우 `git://https://<사용자 깃허브 닉네임>@github.com` 자격 증명의 암호를 갱신해보자.

# References
[1] [workflow scope 오류 해결하기](https://tigris-data-science.tistory.com/entry/workflow-scope-%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0)
[2] [How to resolve "refusing to allow an OAuth App to create or update workflow" on git push](https://stackoverflow.com/questions/64059610/how-to-resolve-refusing-to-allow-an-oauth-app-to-create-or-update-workflow-on)
[3] [어디서 많이 본 workflow Scope 에러 해결법](https://limm-jk.tistory.com/11)
[4] [#1 [remote rejected] refusing to allow an OAuth App to create or update workflow '파일경로' without 'workflow' scope](https://velog.io/@ddeung/1-remote-rejected-refusing-to-allow-an-OAuth-App-to-create-or-update-workflow-%ED%8C%8C%EC%9D%BC-without-workflow-scope)
[5] [Missing OAUTH scope](https://jira.atlassian.com/browse/SRCTREEWIN-12719)
